# Spring properties
spring:
  thymeleaf:
     check-template:false
     enabled:false	
     mode:HTML5
  application:
     name: session-service
 
# Discovery Server Access
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 5555   # HTTP (Tomcat) port
